Avtogaz/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.UI;
using System.Xml;
using System.Xml.XPath;
using Avtogaz.Attributes;
using Avtogaz.Data;
using Avtogaz.Helpers;
using Avtogaz.Models;

using Microsoft.AspNet.Identity;

namespace Avtogaz.Controllers
{
	[Authorize]
	public class AdminController : Controller
	{
		private readonly UserManager<AppUser> userManager;
		private readonly AppDbContext db;

		//Dashboard
		public ActionResult Index()
		{
			return View();
		}

		#region "Constructors"
		public AdminController() : this(Startup.UserManagerFactory.Invoke())
		{
			db = new AppDbContext();
		}

		public AdminController(UserManager<AppUser> userManager)
		{
			this.userManager = userManager;
		}
		#endregion

		#region "Login"

		[AllowAnonymous]
		public ActionResult Login()
		{
			return View();
		}

		[ValidateModelState]
		[ValidateAntiForgeryToken]
		[HttpPost, AllowAnonymous]
		public async Task<ActionResult> Login(LoginModel model)
		{
			var user = await userManager.FindAsync(model.Email, model.Password);

			if (user != null)
			{
				var identity = await userManager.CreateIdentityAsync(user, DefaultAuthenticationTypes.ApplicationCookie);
				HttpContext.GetOwinContext().Authentication.SignIn(identity);

				return RedirectToAction("Index");
			}

			ModelState.AddModelError("", "Введені вами логін або пароль невірні");
			return View(model);
		}

		#endregion

		#region "Change password"

		//Change password
		public ActionResult ChangePassword(string message)
		{
			ViewBag.Message = message;
			return View();
		}

		[HttpPost]
		[ValidateModelState]
		[ValidateAntiForgeryToken]
		public async Task<ActionResult> ChangePassword(ChangePasswordModel model)
		{
			if (model.OldPassword == model.NewPassword)
			{
				ModelState.AddModelError("", "Старий пароль повинен відрізнятися від нового");
				return View(model);
			}

			string userId = User.Identity.GetUserId();
			AppUser user = await userManager.FindByIdAsync(userId);
			if (user == null)
			{
				ModelState.AddModelError("", "Даного користувача не знайдено");
				return View(model);
			}

			IdentityResult result = await userManager.ChangePasswordAsync(userId, model.OldPassword, model.NewPassword);
			if (!result.Succeeded)
			{
				ModelState.AddModelError("", result.Errors.FirstOrDefault());
				return View(model);
			}

			return RedirectToAction("ChangePassword", new { message = "Пароль успішно змінено" });
		}

		#endregion

		#region "Responses"

		[HttpGet]
		public ActionResult Responses()
		{
			var model = db.UserResponses.Where(r => !r.IsDeleted).ToList();

			return View(model);
		}

		[HttpGet]
		public async Task<ActionResult> ReadResponse(int? id)
		{
			if (!id.HasValue)
				return RedirectToAction("Responses");

			UserResponseModel response = await db.UserResponses.FindAsync(id.Value);
			response.IsRead = true;
			await db.SaveChangesAsync();

			return View(response);
		}

		[HttpPost]
		public JsonResult DeleteResponse(int id)
		{
			var response = db.UserResponses.Find(id);
			if (response == null)
				return Json(new { success = "false" });

			response.IsDeleted = true;
			db.SaveChanges();

			return Json(new { success = "true" });
		}

		#endregion

		#region "Prices"

		[HttpGet]
		public ActionResult Prices()
		{
			PriceModel model = db.Prices.OrderByDescending(m => m.ChangeDate).Take(1).SingleOrDefault();
			if (TempData["message"] != null)
				ViewBag.Message = TempData["message"];

			return View(model);
		}

		[ValidateModelState]
		public ActionResult Prices(PriceModel model)
		{
			model.ChangeDate = DateTime.Now;

			db.Prices.Add(model);
			db.SaveChanges();

			TempData["message"] = "success";
			return RedirectToAction("Prices");
		}

		#endregion

		#region "Articles"

		public ActionResult Articles()
		{
			var model = db.Articles.ToList();
			return View(model);
		}

		[HttpGet]
		public ActionResult NewArticle()
		{
			if (TempData["message"] != null)
				ViewBag.Message = TempData["message"];

			return View();
		}

		[HttpPost]
		[ValidateModelState]
		public ActionResult NewArticle(ArticleModel model)
		{
			model.Cut = model.Text.TruncateHtml(600, "...");
			model.PostTime = DateTime.Now;

			db.Articles.Add(model);
			db.SaveChanges();

			TempData["message"] = "Ваша стаття успішно опублікована";
			return RedirectToAction("NewArticle");
		}

		[HttpPost]
		public ActionResult DeleteArticle(int id)
		{
			if (id == 0)
				return HttpNotFound();

			var article = db.Articles.SingleOrDefault(a => a.Id == id);
			if (article == null)
				return Json(new { success = false});

			try
			{
				db.Articles.Remove(article);
				db.SaveChanges();
			}
			catch (Exception)
			{
				return Json(new { success = false });
			}

			return Json(new { success = true });
		}

		public ActionResult EditArticle(int id)
		{
			if (TempData["message"] != null)
				ViewBag.Message = TempData["message"];

			var article = db.Articles.SingleOrDefault(e => e.Id == id);
			if(article == null)
				return HttpNotFound();

			return View(article);
		}

		[HttpPost]
		public ActionResult EditArticle(ArticleModel article)
		{
			var art = db.Articles.Find(article.Id);
			if (art == null)
				return HttpNotFound();

			art.Title = article.Title;
			art.Text = article.Text;
			art.Cut = article.Text.TruncateHtml(600, "...");
			art.PostTime = DateTime.Now;

			db.Entry(art).State = EntityState.Modified;
			db.SaveChanges();

			TempData["message"] = "Стаття успішно відредагована";
			return RedirectToAction("EditArticle", new {Id = article.Id});
		}

		#endregion

		#region Gallery

		public ActionResult Galleries()
		{
			var galleries = db.GalleryItems.ToList();

			return View(galleries);
		}

		public ActionResult EditGallery(int id)
		{
			var model = db.GalleryItems.SingleOrDefault(g => g.Id == id);
			if (model == null)
				return HttpNotFound();

			var categories = db.GalleryCategories.Select(c => new SelectListItem()
			{
				Text = c.Name,
				Value = c.Id.ToString()
			}).ToList();

			var engineTypes = new List<SelectListItem>()
			{
				new SelectListItem() {Text = "Розподілений вприск", Value = "Розподілений вприск"},
				new SelectListItem() {Text = "Безпосередній вприск", Value = "Безпосередній вприск"}
			};

			model.EngineTypes = engineTypes;
			model.Categories = categories;

			return View(model);
		}

		[HttpPost]
		public ActionResult EditGallery(GalleryItem item)
		{
			if (item == null)
				return HttpNotFound();

			var gallery = db.GalleryItems.SingleOrDefault(g => g.Id == item.Id);
			if (gallery == null)
				return HttpNotFound();

			gallery.Title = item.Title;
			gallery.Text = item.Text;
			gallery.CategoryId = item.CategoryId;

			gallery.Mark = item.Mark;
			gallery.Model = item.Model;
			gallery.Year = item.Year;
			gallery.EngineType = item.EngineType;
			gallery.EngineCapacity = item.EngineCapacity;
			gallery.CylinderCount = item.CylinderCount;
			gallery.Power = item.Power;


			if (item.File?.ContentLength > 0)
			{
				ImageResizer.ImageJob i = new ImageResizer.ImageJob(item.File, "~/uploads/gallery_previews/<guid>.<ext>", new
					ImageResizer.ResizeSettings("width=220;height=130;format=jpg;mode=max"));
				i.CreateParentDirectory = true;
				i.Build();
				gallery.Image = System.IO.Path.GetFileName(i.FinalPath);
			}

			db.SaveChanges();

			return RedirectToAction("Galleries");
		}

		[HttpGet]
		public ActionResult NewGallery()
		{
			if (TempData["Message"] != null)
				ViewBag.Message = TempData["Message"];

			var categories = db.GalleryCategories.Select(c => new SelectListItem()
			{
				Text = c.Name,
				Value = c.Id.ToString()
			}).ToList();

			var engineTypes = new List<SelectListItem>()
			{
				new SelectListItem() {Text = "Розподілений вприск", Value = "Розподілений вприск"},
				new SelectListItem() {Text = "Безпосередній вприск", Value = "Безпосередній вприск"}
			};


			var model = new GalleryItem() { Categories = categories, EngineTypes = engineTypes};


			return View(model);
		}

		[HttpPost]
		public ActionResult NewGallery(GalleryItem item)
		{
			try
			{
				if (!ModelState.IsValid)
					return RedirectToAction("NewGallery");

				if (item.File.ContentLength <= 0)
					return null;
				ImageResizer.ImageJob i = new ImageResizer.ImageJob(item.File, "~/uploads/gallery_previews/<guid>.<ext>", new
					ImageResizer.ResizeSettings("width=220;height=130;format=jpg;mode=max"));

				i.CreateParentDirectory = true;
				i.Build();

				item.Image = System.IO.Path.GetFileName(i.FinalPath);
				item.PostTime = DateTime.Now;
				db.GalleryItems.Add(item);
				db.SaveChanges();

				//TODO: add categories

				TempData["Message"] = "Ваша публікація успішно опублікована";
				return RedirectToAction("NewGallery");
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("", ex.Message);
				return View(item);
			}
		}

		[HttpGet]
		public ActionResult GalleryCategories()
		{
			var model = db.GalleryCategories.ToList();
			return View(model);
		}

		[HttpPost]
		public ActionResult GalleryCategories(GalleryCategory category)
		{
			try
			{
				db.GalleryCategories.Add(category);
				db.SaveChanges();
			}
			catch (Exception ex)
			{
				ModelState.AddModelError("", ex.Message);
			}

			var model = db.GalleryCategories.ToList();
			return View(model);
		}

		public JsonResult RemoveGalleryCategory(int id)
		{
			try
			{
				var category = db.GalleryCategories.SingleOrDefault(c => c.Id == id);
				if (category == null)
					throw new Exception("Категорія з таким ID не знайдена");
				if (category.Items.Count > 0)
					throw new Exception("Неможливо видалити непусту категорію");

				db.GalleryCategories.Remove(category);
				db.SaveChanges();

				return Json(new { Success = true, Id = id });
			}
			catch (Exception ex)
			{
				return Json(new { Success = false, Message = ex.Message });
			}
		}
		#endregion

		#region FAQ

Avtogaz/Controllers/ArticlesController.cs
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace Avtogaz.Controllers
{
    public class ArticlesController : Controller
    {
	    private readonly AppDbContext db;

	    public ArticlesController()
	    {
		    this.db = new AppDbContext();
	    }

	    // GET: Articles
        public async Task<ActionResult> Index()
        {
	        var articles = await db.Articles.OrderByDescending(a => a.PostTime).ToListAsync();

			return View(articles);
        }

	    public async Task<ActionResult> Article(int id = 1)
	    {
		    var article = await db.Articles.FindAsync(id);
		    if (article == null)
			    return HttpNotFound();

		    return View(article);
	    }
    }
}

Avtogaz/Controllers/GalleryController.cs
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using Avtogaz.Data;
using Avtogaz.Helpers;
using Avtogaz.Models;

namespace Avtogaz.Controllers
{
	public class GalleryController : Controller
	{
		public AppDbContext db { get; set; }

		public GalleryController()
		{
			db = new AppDbContext();
		}

		// GET: Gallery
		public ActionResult Index(int? category)
		{
			var previews = new List<GalleryPreview>();

			if (category.HasValue)
			{
				previews = db.GalleryItems.AsNoTracking().
					Where(g => g.CategoryId == category.Value).
					AsEnumerable().
					Select(g => new GalleryPreview()
					{
						Id = g.Id,
						Title = g.Title,
						Model = g.Model,
						CylinderCount = g.CylinderCount,
						EngineCapacity = g.EngineCapacity,
						EngineType = g.EngineType,
						Mark = g.Mark,
						Power = g.Power,
						Year = g.Year,
						Image = System.IO.Path.Combine(Constants.GALLERY_PREVIEWS_PATH, g.Image)
					}).ToList();
			}
			else
			{
				previews = db.GalleryItems.AsNoTracking().
					AsEnumerable().
					Select(g => new GalleryPreview()
					{
						Id = g.Id,
						Title = g.Title,
						Model = g.Model,
						CylinderCount = g.CylinderCount,
						EngineCapacity = g.EngineCapacity,
						EngineType = g.EngineType,
						Mark = g.Mark,
						Power = g.Power,
						Year = g.Year,
						Image = System.IO.Path.Combine(Constants.GALLERY_PREVIEWS_PATH, g.Image)
					}).ToList();
			}


			//TODO: add image

			var categories = db.GalleryCategories.ToList();
			var model = new GalleryViewModel()
			{
				Categories = categories,
				Previews = previews
			};

			return View(model);
		}
	
		public ActionResult Job(int? id)
		{
			if(!id.HasValue)
				return HttpNotFound();

			GalleryItem job = db.GalleryItems.SingleOrDefault(j => j.Id == id.Value);

			return View(job);
		}
	}
}

Avtogaz/Views/Admin/Articles.cshtml
@model ICollection<Avtogaz.Models.ArticleModel>

    @{
    ViewBag.Title = "Статті";
    }

    <style>
        .card {
            margin-bottom: 10px;
        }

        .card-content {
            padding: 10px;
            font-size: 14px;
        }

        .floatright {
            float: right;
        }

        .article-title {
            display: inline-block;
            max-width: 565px;
        }
    </style>

    <h2>
        <i class="fa fa-newspaper-o"></i> Статті
    </h2>

    @foreach (var article in Model)
    {
        <div class="card card-1">
            <div class="card-content">
                <div class="article-title">
                    <a href="@Url.Action("Article", "Articles" , new {Id=article.Id})" target="_blank">@article.Title</a>
                    (@article.PostTime.ToShortDateString())
                </div>
                <div class="floatright">
                    <a href="@Url.Action("EditArticle", "Admin", new { Id = article.Id })">Редагувати</a> |
                    <a class="remove-article-btn" data-id="@article.Id" href="#">Видалити</a>
                </div>
            </div>
        </div>
    }

@section scripts
{
    <script>
        $(function () {
            $(".remove-article-btn").click(function (e) {
                e.preventDefault();
                if (!confirm("Ви дійсно бажаєте видалити дану статтю?"))
                    return;

                var ids = $(this).data("id");
                var block = $(this).closest(".card");


                $.ajax({
                    url: "/Admin/DeleteArticle",
                    data: { id : ids},
                    type: "POST",
                    success: function(response) {
                        if (response.success) {
                            $(block).fadeOut();
                        }
                    }
                })
            });
        })
    </script>
}

Avtogaz/Views/Admin/ChangePassword.cshtml
@model Avtogaz.Models.ChangePasswordModel

@{
	ViewBag.Title = "Зміна паролю";
}

<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>Зміна паролю</h3>
		</div>
		<div class="module-body">

			@if (!ViewContext.ViewData.ModelState.IsValid)
			{
				<div class="alert alert-error">
					<button type="button" class="close" data-dismiss="alert">×</button>
					@Html.ValidationSummary()
				</div>
			}

			@if (ViewBag.Message != null)
			{
				<div class="alert alert-success">
					<button type="button" class="close" data-dismiss="alert">×</button>
					@ViewBag.Message
				</div>
			}


			@using (Html.BeginForm("ChangePassword", "Admin", FormMethod.Post, new { @class = "form-horizontal row-fluid" }))
			{
				@Html.AntiForgeryToken()

				<div class="control-group">
					<label class="control-label" for="basicinput">Старий пароль</label>
					<div class="controls">
						@Html.TextBoxFor(m => m.OldPassword, new { @class="span12" })
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="basicinput">Новий пароль</label>
					<div class="controls">
						@Html.PasswordFor(m => m.NewPassword, new { @class = "span12" })
					</div>
				</div>

				<div class="control-group">
					<label class="control-label" for="basicinput">Підтвердіть пароль</label>
					<div class="controls">
						@Html.PasswordFor(m => m.ConfirmPassword, new { @class = "span12" })
					</div>
				</div>

				<div class="control-group">
					<div class="controls align-right">
						<button type="submit" class="btn">Змінити пароль</button>
					</div>
				</div>
			}
		</div>
	</div>
</div>

Avtogaz/Views/Admin/EditArticle.cshtml
@model Avtogaz.Models.ArticleModel

@{
    ViewBag.Title = Model.Title + " | редагування";
}

<h2><i class="fa fa-pencil"></i> Редагування статті</h2>

@if (ViewBag.Message != null)
{
    <div class="alert alert-success">
        <i class="fa fa-check"></i> @ViewBag.Message
    </div>
}

@using (Html.BeginForm("EditArticle", "Admin", FormMethod.Post, new { @id = "article-form" }))
{
	@Html.TextBoxFor(m => m.Title, new { @class = "span9", placeholder = "Введіть назву статті..." })

	@Html.TextBoxFor(m => m.Text, new { @class = "redactor" })


    <div class="post-div">
        <span class="pull-left"><i>Підказка: перехід на новий рядок - SHIFT+ENTER</i></span>

        <a href="#" id="post-article" class="btn btn-success">Опублікувати статтю</a>
    </div>
    <div class="clearfix"></div>
}

<script src="~/Scripts/admin/tinymce/tinymce.min.js"></script>
@section scripts
{
    <script>
		    $(function () {
			    tinymce.init({
				    selector: ".redactor",
				    height: 400,
				    menubar: false,
				    language: "uk_UA",
				    image_advtab: true,
				    plugins: "fullscreen table link searchreplace media textcolor autosave preview image",
				    toolbar: "undo redo | styleselect fontsizeselect forecolor backcolor removeformat | alignleft aligncenter alignright | bullist numlist | link media image table | " +
					    "fullscreen preview",
				    file_browser_callback: RoxyFileBrowser
			    });

			    function RoxyFileBrowser(field_name, url, type, win) {
				    var roxyFileman = '/fileman/index.html';
				    if (roxyFileman.indexOf("?") < 0) {
					    roxyFileman += "?type=" + type;
				    }
				    else {
					    roxyFileman += "&type=" + type;
				    }
				    roxyFileman += '&input=' + field_name + '&value=' + win.document.getElementById(field_name).value;
				    if (tinyMCE.activeEditor.settings.language) {
					    roxyFileman += '&langCode=' + tinyMCE.activeEditor.settings.language;
				    }
				    tinyMCE.activeEditor.windowManager.open({
					    file: roxyFileman,
					    title: 'Файловий менеджер',
					    width: 850,
					    height: 650,
					    resizable: "yes",
					    plugins: "media",
					    inline: "yes",
					    close_previous: "no"
				    }, { window: win, input: field_name });
				    return false;
			    }

			    $("#post-article").click(function(e) {
				    e.preventDefault();

				    $("#article-form").submit();
			    });
		    })
    </script>
}

Avtogaz/Views/Admin/EditGallery.cshtml
@model Avtogaz.Models.GalleryItem

@{
    ViewBag.Title = Model.Title;
}

<style>
    .panel-heading {
        background-color: #eee;
    }

    .note-editor {
        border: 1px solid rgba(169, 169, 169, 0.32);
    }

    .post-div {
        margin-top: 20px;
        text-align: right;
    }
</style>


<h2><i class="fa fa-newspaper-o"></i> Редагування публікації</h2>

@if (ViewBag.Message != null)
{
    <div class="alert alert-success">
        @ViewBag.Message
    </div>
}

@using (Html.BeginForm("EditGallery", "Admin", FormMethod.Post, new { @id = "article-form", enctype = "multipart/form-data" }))
{
	@Html.TextBoxFor(m => m.Title, new { @class = "span9", placeholder = "Введіть назву статті..." })
    <div class="well">
        <div class="row">
            <div class="span3">
                @Html.TextBoxFor(m => m.Mark, new {placeholder = "Марка"})
                @Html.TextBoxFor(m => m.Model, new {placeholder = "Модель"})
                @Html.TextBoxFor(m => m.Year, new {placeholder = "Рік випуску"})
            </div>
            <div class="span3">
                @Html.TextBoxFor(m => m.EngineCapacity, new {placeholder = "Об'єм двигуна"})
                @Html.TextBoxFor(m => m.CylinderCount, new {placeholder = "Кількість циліндрів"})
            </div>
            <div class="span2">
                @Html.TextBoxFor(m => m.Power, new {placeholder = "Потужність"})
                @Html.DropDownListFor(m => m.EngineType, Model.EngineTypes)
                @Html.DropDownListFor(m => m.CategoryId, Model.Categories)
            </div>
        </div>
    </div>

    <div class="well">
        <i class="fa fa-image"></i> Зображення:<br /><br />
        <input type="file" name="File" />
    </div>

	@Html.ValidationSummary()
	@Html.TextBoxFor(m => m.Text, new { @class = "redactor" })


    <div class="post-div">
        <span class="pull-left"><i>Підказка: перехід на новий рядок - SHIFT+ENTER</i></span>

        <a href="#" id="post-article" class="btn btn-success">Опублікувати статтю</a>
    </div>
    <div class="clearfix"></div>
}

<script src="~/Scripts/admin/tinymce/tinymce.min.js"></script>
@section scripts
{
<script>
		$(function () {
			tinymce.init({
				selector: ".redactor",
				height: 400,
				menubar: false,
				language: "uk_UA",
				plugins: "fullscreen table link searchreplace media textcolor autosave preview image",
				toolbar: "undo redo | styleselect fontsizeselect forecolor backcolor removeformat | bullist numlist | link media image table | " +
					"fullscreen preview",
				file_browser_callback: RoxyFileBrowser
			});

			function RoxyFileBrowser(field_name, url, type, win) {
				var roxyFileman = '/fileman/index.html';
				if (roxyFileman.indexOf("?") < 0) {
					roxyFileman += "?type=" + type;
				}
				else {
					roxyFileman += "&type=" + type;
				}
				roxyFileman += '&input=' + field_name + '&value=' + win.document.getElementById(field_name).value;
				if (tinyMCE.activeEditor.settings.language) {
					roxyFileman += '&langCode=' + tinyMCE.activeEditor.settings.language;
				}
				tinyMCE.activeEditor.windowManager.open({
					file: roxyFileman,
					title: 'Файловий менеджер',
					width: 850,
					height: 650,
					resizable: "yes",
					plugins: "media",
					inline: "yes",
					close_previous: "no"
				}, { window: win, input: field_name });
				return false;
			}


			$("#post-article").click(function(e) {
				e.preventDefault();

				$("#article-form").submit();
			});
		})
</script>
}

Avtogaz/Views/Admin/Faq.cshtml
@model Avtogaz.Models.FaqViewModel

@{
	ViewBag.Title = "FAQ";
}

<style>
	.table {
		background-color: white;
	}

	.table tr td {
		vertical-align: middle;
	}

	.faq-edit {
		color: #2E87ED;
	}

	.faq-delete {
		color: crimson;
	}
</style>

<h2><i class="fa fa-question-circle"></i> FAQ</h2><hr />

@using (Html.BeginForm("AddFaq", "Admin", FormMethod.Post, new { id = "qqq" }))
{
	<div class="well">
		<div class="eight columns">Питання</div>
		<div class="eight columns">
			<input type="text" name="Title" style="width: 100%" />

			<div class="eight columns">Відповідь</div>
			<div class="eight columns">
				<textarea name="Text" style="width: 100%;"></textarea>
				
			</div>

			<div class="eight columns">
				<div class="eight columns">Категорія</div>
				<div class="align-left">
					@Html.DropDownListFor(m => m.CategoryId, Model.Categories)
				</div>
			</div>

			<div style="margin-top: 10px;">
				@Html.CheckBox("ShowInSideBlock")
				<label for="ShowInSideBlock" style="display: inline-block">Показувати в блоці найчастіших питань</label>
			</div>

			<div class="align-right">
				<input type="submit" class="btn btn-success" value="Додати"/>

			</div>

		</div>
	</div>
}


<table class="table table-bordered">
	<thead>
		<tr>
			<th width="200">Питання</th>
			<th>Відповідь</th>
			<th width="50S">В блоці</th>
			<th width="50">Дії</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var faq in Model.Items)
		{
			<tr>
				<td>@faq.Title</td>
				<td>@faq.Text</td>
				<td>
					@if (faq.ShowInSideBlock)
					{
						@:✓
					}
				</td>
				<td>
					<span class="faq-options" data-id="@faq.Id">
						<i class="fa fa-edit faq-edit"></i>
						<i class="fa fa-remove faq-delete"></i>
					</span>
				</td>
			</tr>
		}
	</tbody>
</table>

@section scripts
{
	<script>
		$(function() {
			$(".faq-delete").click(function () {

				if (!confirm("Ви дійсно бажаєте видалити даний FAQ?"))
					return;

				var self = $(this);
				var id = $(this).parent().data("id");

				$.post("@Url.Action("DeleteFaqItem")", {
					Id: id
				},
				function(response) {
					if (response.Success) {
						$(self).parent().closest("tr").fadeOut("slow");
					} else {
						alert(response.Message);
					}
				});
			})
		})
	</script>
}

Avtogaz/Views/Admin/Galleries.cshtml
@model System.Collections.Generic.List<Avtogaz.Models.GalleryItem>

    @{
    ViewBag.Title = "Список робіт";
    }

    <style>
        .card {
            margin-bottom: 10px;
        }

        .card-content {
            padding: 10px;
            font-size: 14px;
        }

        .floatright {
            float: right;
        }

        .article-title {
            display: inline-block;
            max-width: 565px;
        }
    </style>

    <h2>
        <i class="fa fa-bookmark"></i> Список робіт
    </h2>

    @foreach (var work in Model)
    {
    <div class="card card-1">
        <div class="card-content">
            <div class="article-title">
                <a href="@Url.Action("Job", "Gallery" , new {Id=work.Id})" target="_blank">@work.Title</a>
            </div>
            <div class="floatright">
                <a href="@Url.Action("EditGallery", "Admin" , new { Id=work.Id })">Редагувати</a> |
                <a class="remove-article-btn" data-id="@work.Id" href="#">Видалити</a>
            </div>
        </div>
    </div>
    }

Avtogaz/Views/Admin/ReadResponse.cshtml
@model Avtogaz.Models.UserResponseModel

@{
	ViewBag.Title = Model.Email;
}

<div class="content">
	<div class="module">
		<div class="module-head">
			<h3>
				Лист від @Model.Name (@Model.Email)
			</h3>
		</div>
		<div class="module-body">
			@Model.Text
		</div>
	</div>

	<div class="row">
		<div class="span9 clearfix">
			@Html.ActionLink("Назад до списку", "Responses", null, new { @class="btn btn-default" })
		</div>
	</div>

</div>